"""
Custom storage backends for Bluewave Academy.

All user-uploaded media (PDFs, videos, images, documents) goes to
Supabase Storage via its S3-compatible API.

Supabase exposes S3 at:
  https://<project-ref>.supabase.co/storage/v1/s3

Each model field's upload_to= path becomes the object key inside the bucket.

Buckets used:
  - SUPABASE_MEDIA_BUCKET  (default: "media")  — profile pics, blog images,
                                                  tutorial thumbnails/videos,
                                                  classroom materials, PDF submissions
  - SUPABASE_PAPERS_BUCKET (default: "papers") — SpecialPaper objects (existing flow)
"""

from storages.backends.s3boto3 import S3Boto3Storage
from django.conf import settings


class SupabaseMediaStorage(S3Boto3Storage):
    """
    Default media file backend.
    Writes to the SUPABASE_MEDIA_BUCKET bucket.
    Files are private by default; access is controlled via signed URLs
    generated by Supabase or served through the app.
    """

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("bucket_name", settings.SUPABASE_MEDIA_BUCKET)
        kwargs.setdefault("region_name", settings.SUPABASE_S3_REGION)
        kwargs.setdefault("endpoint_url", settings.SUPABASE_S3_ENDPOINT)
        kwargs.setdefault("access_key", settings.SUPABASE_S3_ACCESS_KEY)
        kwargs.setdefault("secret_key", settings.SUPABASE_S3_SECRET_KEY)
        kwargs.setdefault("default_acl", "private")
        kwargs.setdefault("file_overwrite", False)
        kwargs.setdefault("querystring_auth", True)        # signed URLs
        kwargs.setdefault("querystring_expire", 3600)      # 1-hour default expiry
        kwargs.setdefault("object_parameters", {
            "CacheControl": "max-age=86400",               # 24-hour CDN hint
        })
        super().__init__(*args, **kwargs)


class SupabasePublicMediaStorage(S3Boto3Storage):
    """
    Public media backend — for assets that should be world-readable
    (e.g. blog post cover images, tutorial thumbnails).
    Set a field's storage= to this class when public access is desired.
    """

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("bucket_name", settings.SUPABASE_MEDIA_BUCKET)
        kwargs.setdefault("region_name", settings.SUPABASE_S3_REGION)
        kwargs.setdefault("endpoint_url", settings.SUPABASE_S3_ENDPOINT)
        kwargs.setdefault("access_key", settings.SUPABASE_S3_ACCESS_KEY)
        kwargs.setdefault("secret_key", settings.SUPABASE_S3_SECRET_KEY)
        kwargs.setdefault("default_acl", "public-read")
        kwargs.setdefault("file_overwrite", False)
        kwargs.setdefault("querystring_auth", False)       # plain public URL
        kwargs.setdefault("object_parameters", {
            "CacheControl": "max-age=86400",
        })
        super().__init__(*args, **kwargs)


class SupabasePapersStorage(S3Boto3Storage):
    """
    Storage backend for the SpecialPaper bucket.
    Files are always private; the existing signed-URL flow in
    examinator_views._get_supabase_url() continues to handle downloads.
    """

    def __init__(self, *args, **kwargs):
        kwargs.setdefault("bucket_name", settings.SUPABASE_PAPERS_BUCKET)
        kwargs.setdefault("region_name", settings.SUPABASE_S3_REGION)
        kwargs.setdefault("endpoint_url", settings.SUPABASE_S3_ENDPOINT)
        kwargs.setdefault("access_key", settings.SUPABASE_S3_ACCESS_KEY)
        kwargs.setdefault("secret_key", settings.SUPABASE_S3_SECRET_KEY)
        kwargs.setdefault("default_acl", "private")
        kwargs.setdefault("file_overwrite", False)
        kwargs.setdefault("querystring_auth", True)
        kwargs.setdefault("querystring_expire", 300)       # 5 min for paper downloads
        super().__init__(*args, **kwargs)


def get_signed_url(bucket_name: str, path: str, expiry_seconds: int = 300) -> str | None:
    """
    Generate a signed download URL for any file in a Supabase bucket.

    Uses the Supabase Python client (existing dependency).
    Falls back gracefully if Supabase credentials are not configured.

    Args:
        bucket_name: Name of the Supabase storage bucket.
        path:        Object path inside the bucket (e.g. "papers/2024/cs-p1.pdf").
        expiry_seconds: How long the URL should remain valid.

    Returns:
        Signed URL string, or None if unavailable.
    """
    import os
    supabase_url = os.environ.get("SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SERVICE_KEY")

    if not supabase_url or not supabase_key:
        return None

    try:
        from supabase import create_client
        client = create_client(supabase_url, supabase_key)
        response = client.storage.from_(bucket_name).create_signed_url(path, expiry_seconds)
        return response.get("signedURL") or response.get("signedUrl")
    except Exception as exc:
        import logging
        logging.getLogger(__name__).error("[Supabase] Signed URL error for %s: %s", path, exc)
        return None
