# Generated by Django 5.2.1 on 2026-05-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_color', models.CharField(default='#2563eb', help_text='Hex color for classroom card', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('quiz', 'Online Quiz (MCQ / Short Answer)'), ('coding', 'Coding Practical'), ('pdf_upload', 'Written / PDF Upload'), ('timed_quiz', 'Timed Quiz')], default='quiz', max_length=20)),
                ('rubric', models.TextField(blank=True, help_text='Grading rubric shown to the AI grader')),
                ('answer_key', models.TextField(blank=True, help_text='Model answer or expected output')),
                ('total_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=50)),
                ('deadline', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60, help_text='Time limit in minutes (0 = no limit)')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_resubmit', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('programming_language', models.CharField(blank=True, help_text='For coding assignments: python, java, javascript, etc.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='siteapp.classroom')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('zimsec_cs', 'ZIMSEC Computer Science'), ('zimsec_math', 'ZIMSEC Mathematics'), ('zimsec_phy', 'ZIMSEC Physics'), ('alevel_cs', 'A-Level CS'), ('olevel_cs', 'O-Level CS'), ('other', 'Other')], default='zimsec_cs', max_length=30)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('paper_number', models.CharField(blank=True, help_text='e.g. Paper 1, Paper 2, Solutions', max_length=20)),
                ('supabase_path', models.CharField(help_text='Path in Supabase storage bucket, e.g. papers/2023/cs-p1.pdf', max_length=500)),
                ('is_public', models.BooleanField(default=False, help_text='If False, login is required to download')),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Special Paper',
                'verbose_name_plural': 'Special Papers',
                'ordering': ['-year', 'category', 'paper_number'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='siteapp.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Text / short-answer / essay response')),
                ('code_text', models.TextField(blank=True, help_text='Code submission for coding practicals')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF for written/handwritten submissions', null=True, upload_to='submissions/pdfs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('grading', 'Grading in Progress'), ('graded', 'Graded'), ('failed', 'Grading Failed'), ('manual_review', 'Needs Manual Review')], default='pending', max_length=20)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ai_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_strengths', models.JSONField(blank=True, default=list)),
                ('ai_improvements', models.JSONField(blank=True, default=list)),
                ('ai_improvement_tips', models.JSONField(blank=True, default=list)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('instructor_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('report_sent', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='siteapp.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
