# Generated by Django 5.2.1 on 2026-05-12 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_classroom_assignment_specialpaper_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Database', 'Database'), ('Algorithms', 'Algorithms'), ('Career Tips', 'Career Tips'), ('Academy News', 'Academy News'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics/'),
        ),
    ]
