# Generated by Django 5.2.1 on 2026-06-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_blogpost_author_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tutorials/thumbnails/')),
                ('video_type', models.CharField(choices=[('file', 'Uploaded File'), ('url', 'YouTube / External URL')], default='url', max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tutorials/videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other embed-compatible URL')),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Database', 'Database'), ('Algorithms', 'Algorithms'), ('Computer Science', 'Computer Science'), ('Career Tips', 'Career Tips'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_pct', models.FloatField(default=0, help_text='0-100 percent watched')),
                ('completed', models.BooleanField(default=False)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='siteapp.tutorial')),
            ],
            options={
                'verbose_name': 'Video Progress',
                'verbose_name_plural': 'Video Progress Records',
                'unique_together': {('student', 'tutorial')},
            },
        ),
    ]
